#### 03_Numpy를 사용하여 이미지 저장 시 효율 비교

In [1]:
# !pip install pillow

In [2]:
import numpy as np
from PIL import Image

In [4]:
# 이미지 불러오기
img = Image.open('../99_Studyfile/Sample/cat.png').convert('L') # 그레이 스케일 변환
print(img)

<PIL.Image.Image image mode=L size=310x162 at 0x1080836A0>


In [5]:
img_array = np.array(img)
print(img_array)

[[222 222 222 ... 169 169 169]
 [223 223 223 ... 168 168 168]
 [223 223 223 ... 165 165 165]
 ...
 [219 219 222 ... 235 234 234]
 [221 222 224 ... 236 236 235]
 [221 222 224 ... 236 236 235]]


In [7]:
np.save('../99_Studyfile/Output/pil_image.npy',img_array)

In [8]:
img_array1 = np.load('../99_Studyfile/Output/pil_image.npy')
print(img_array1)

[[222 222 222 ... 169 169 169]
 [223 223 223 ... 168 168 168]
 [223 223 223 ... 165 165 165]
 ...
 [219 219 222 ... 235 234 234]
 [221 222 224 ... 236 236 235]
 [221 222 224 ... 236 236 235]]


In [11]:
# 다시 PIL Img로 변환
img = Image.fromarray(np.uint8(img_array1))
img.save('../99_Studyfile/Output/image_numpy.png')

In [12]:
import os
np_save_size = os.path.getsize('../99_Studyfile/Output/pil_image.npy')

pil_save_size = os.path.getsize('../99_Studyfile/Output/image_numpy.png')
print(np_save_size, 'bytes')
print(pil_save_size, 'bytes')

50348 bytes
26813 bytes
